### PR TITLE
Various improvements.

### PR DESCRIPTION
**Pull request by Drup**
Various improvements, a lot of cosmetic changes to make it more
ocaml-y (you have a thing with parens, don't you ? :)

I don't like the organisation of the file, but since I don't like the
MVC approach, that's irrelevant. :p

It could use the reactive stuff we have in jsoo, I didn't tried yet.

### CODE REVIEW

**Comment by Drup** [comment]
Finally. the right one.

**Comment by slegrand45** [comment]
Thank you very much for your patches!

**Comment by Drup** [comment]
Do you want to try to do the react version ?

**Comment by slegrand45** [comment]
Sure, i would be really interested! Unfortunately, i don't really know where to begin. I saw the Lwt_react and Tyxml_js.​R modules. But the doc is too sparse for me to be able to grasp the details. So, if you have some examples and/or other docs, i'm particularly interested.

**Comment by Drup** [comment]
You can start by reading the [react tutorial](http://erratique.ch/software/react/doc/React) then [this tutorial](http://ocsigen.org/tuto/4.2/manual/reactivemediaplayer) (which is about eliom, but the knowledge should transfer easily).

**Comment by slegrand45** [comment]
Thank you. I will take a look and try to make a react version.

**Comment by slegrand45** [comment]
I made a first React version (new branch named "react"). The diff can be viewed here: https://github.com/slegrand45/todomvc/compare/js_of_ocaml...slegrand45:react

But i'm not sure if it's enough reactive :-)

**Comment by Drup** [comment]
yeah, you can do much better than that.

**Comment by slegrand45** [comment]
Second attempt done: https://github.com/slegrand45/todomvc/commit/03e217ebd347cb48e23849bdf369eda270bd7b48

But i'm not satisfied... At least, this new version avoids a complete page refresh when the view is updated. Basically, i think i understand the react primary functions. But i still can't see what would be the global design of a real react application. Not to mention the Tyxml_js.​R module which has been for now reluctant to all my tests...

**Comment by slegrand45** [comment]
I think it's finally much better now: https://github.com/slegrand45/todomvc/tree/react/examples/js_of_ocaml

**Comment by Drup** [comment]
You figured out how to use the `R` module, good! It's indeed much better now.

**Comment by Drup** [comment]
If you are interested/motivated, we would happily welcome a small write up on the ocsigen blog. ;)

**Comment by slegrand45** [comment]
No problem, i will do! I didn't know there was one by the way :smiley:

**Pull request merged**
